# Generated by Django 3.2.5 on 2021-07-19 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210719_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(default='新しいノート', max_length=30, verbose_name='題名'),
        ),
    ]
