# Generated by Django 3.2.5 on 2021-07-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='translation',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
