# Generated by Django 3.2.5 on 2021-07-23 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_text_translation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='words',
            field=models.CharField(max_length=200),
        ),
    ]
