# Generated by Django 3.2.5 on 2021-07-23 05:57

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_text_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='sentence',
            field=models.CharField(default='', max_length=800),
        ),
        migrations.AlterField(
            model_name='text',
            name='words',
            field=django_mysql.models.ListCharField(models.CharField(max_length=20), max_length=840, size=40),
        ),
    ]
