# Generated by Django 3.2.5 on 2021-07-23 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210723_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='words',
        ),
    ]
