# Generated by Django 3.2.5 on 2021-07-24 07:16

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_text_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='if_hide',
            field=django_mysql.models.ListCharField(models.CharField(max_length=1), default='', max_length=80, size=40),
        ),
    ]
