# Generated by Django 3.2.5 on 2021-07-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_text_if_hide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(default='', max_length=30, verbose_name='題名'),
        ),
    ]
