# Generated by Django 3.2.5 on 2021-07-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_note_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='translation',
            field=models.CharField(max_length=400),
        ),
    ]
