# Generated by Django 3.2.5 on 2021-08-11 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_fav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fav',
            name='note_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.note'),
        ),
    ]
