# Generated by Django 3.2.5 on 2021-08-15 07:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_rename_note_id_fav_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='fav',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='作成日時'),
            preserve_default=False,
        ),
    ]
