# Generated by Django 3.2.5 on 2021-08-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_fav_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=20, verbose_name='題名'),
        ),
    ]
